name: Build & Test

on:
  push:
    branches: [ "main", "rel-*" ]

env:
  NAME: World

jobs:

  build:

    runs-on: ubuntu-20.04

    timeout-minutes: 5

    steps:

      - name: Greet user
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

  test:

    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        browser: [chrome, firefox]
        device: [desktop, mobile]
        include:
          - os: windows-latest
            browser: edge
            device: desktop
        exclude:
          - os: ubuntu-20.04
            browser: chrome
            device: mobile

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    needs: build

    env:
      NAME: Planet

    steps:

      - name: Demo of how to access current matrix context
        run: |
          echo "Browser: ${{ aaa.browser }}
          echo "Device: ${{ matrix.device }}"

      - name: Step inside test job
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"


